name: 项目评分
description: 选择你的评分并提交
title: Rating
labels:
  - rating
body:
  - type: dropdown
    id: rating
    attributes:
      label: 评分
      options:
        - 0.5
        - 1.0
        - 1.5
        - 2.0
        - 2.5
        - 3.0
        - 3.5
        - 4.0
        - 4.5
        - 5.0
    validations:
      required: true
